### ISSUE TITLE
'vagrant up' does not complete - "must accept keys when running highstate with master!"

### ISSUE THREAD

**Issue by TheBigBear** [tinyclues/saltpad#107]
when I run 'vagrant up' on the new saltpad (js) I get:

```
vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

salt:
* You must accept keys when running highstate with master!
```

**Comment by Lothiraldan** [comment]
Humm, weird, I will check it out

**Comment by Lothiraldan** [comment]
Which vagrant version do you use?

**Comment by TheBigBear** [comment]
OK, sorry, this was a heavily modified vagrant 'default'  box. I thought the Vagrantfile would do a new install. sorry. 
I have now destroyed this virtual machine and am starting with a new copy of the default ubuntu box. closing this. 
unfortunatley the new box fails provision, as well, so I will open up a new issue on that with all the details and version numbers etc.

**Comment by TheBigBear** [comment]
OK, there was more to it then that.

I was running vagrant 1.7.4 which impacts some things, AND I also had vagrant-salt plugin 0.4.0 installed. 

Once I upgraded vagrant to latest 1.8.1 and removed the vagrant-salt plugin the 'vagrant up' cmd strated working ...
