### ISSUE TITLE
XMLHttpRequest cannot load https://saltpad.example.com:5417/login

### ISSUE THREAD

**Issue by TheBigBear** [tinyclues/saltpad#116]
I am running on a 2015.8.3 master with tronado 4.1.2 on port 5417, and the ```cors_origin: '*'``` line active and with SSL enabled I do not get past the login screen. 

Instead I get:

```
XMLHttpRequest cannot load https://saltpad.<xxx.xxx>:5417/login. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://saltpad.<xxx.xxx>' is therefore not allowed access. The response had HTTP status code 405.
```

<img width="1099" alt="error 405" src="https://cloud.githubusercontent.com/assets/471105/12292414/da01f706-b9e4-11e5-840b-64be8b9893a9.png">

**Comment by Lothiraldan** [comment]
Could you please paste the output of this command from the server where salt-api is running: `curl -i -X OPTIONS http://localhost:5417/login -H "Access-Control-Request-Headers: accept, content-type"`?

**Comment by TheBigBear** [comment]
Here is my output:

As you pasted it, in http mode (which my server wil not allow as it re-writes all http requests to it to https requests, I get.

```
root@localhost:/opt/saltpad# curl -i -X OPTIONS http://localhost:5417/login -H "Access-Control-Request-Headers: accept, content-type"
curl: (56) Failure when receiving data from the peer
```


And if I do it against the https secure URL but using the wrong hapache virtualhost name 'localhost' , instead of it's real 'saltpad.xx.xxx' name, I get:

```
root@localhost:/opt/saltpad# curl -i -X OPTIONS https://localhost:5417/login -H "Access-Control-Request-Headers: accept, content-type"
curl: (51) SSL: certificate subject name 'saltpad.<xxx.xxx>' does not match target host name 'localhost'
```

And if I add '-k' to have curl suppress or ignore certifcate warnings, I get:

```
root@localhost:/opt/saltpad# curl -k -i -X OPTIONS https://localhost:5417/login -H "Access-Control-Request-Headers: accept, content-type"
HTTP/1.1 405 Method Not Allowed
Date: Wed, 13 Jan 2016 14:38:28 GMT
Content-Length: 321
Content-Type: text/plain
Server: TornadoServer/4.2.1

Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/tornado/web.py", line 1412, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/lib64/python2.6/site-packages/tornado/web.py", line 231, in options
    raise HTTPError(405)
HTTPError: HTTP 405: Method Not Allowed
```

And if I now do the same thing against the real salt-api host first over http I get:

```
root@localhost:/opt/saltpad# curl -i -X OPTIONS http://saltpad.uk.om.org:5417/login -H "Access-Control-Request-Headers: accept, content-type"
curl: (56) Failure when receiving data from the peer
```

And here is the https output
```
root@localhost:/opt/saltpad# curl  -i -X OPTIONS https://saltpad.uk.om.org:5417/login -H "Access-Control-Request-Headers: accept, content-type"
HTTP/1.1 405 Method Not Allowed
Date: Wed, 13 Jan 2016 14:39:21 GMT
Content-Length: 321
Content-Type: text/plain
Server: TornadoServer/4.2.1

Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/tornado/web.py", line 1412, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/lib64/python2.6/site-packages/tornado/web.py", line 231, in options
    raise HTTPError(405)
HTTPError: HTTP 405: Method Not Allowed
```

Hope this helps.

**Comment by Lothiraldan** [comment]
Just for clarification, the idea was to query directly salt-api. On which port your salt-api is configured to listen?

**Comment by TheBigBear** [comment]
```
/etc/salt/master:
...
<cut some>

#rest_cherrypi:
rest_tornado:
  port: 5417
  debug: true
  #expire_responses : False
  ssl_crt: /etc/pki/tls/certs/saltpad_uk_om_org.crt
  ssl_key: /etc/pki/tls/private/saltpad.key
  host: 0.0.0.0
  # host: 127.0.0.1
  disable_ssl: False
  websockets: True
  cors_origin: '*'

<cut rest>
...
```

**Comment by Lothiraldan** [comment]
Could you give me the output of `salt-api --versions-report`?

**Comment by TheBigBear** [comment]
```
root@localhost:/var/log/salt# salt-api --versions-report
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.09
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: 0.20.3
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.12.1.el6.x86_64
         system: CentOS 6.7 Final
```

**Comment by Lothiraldan** [comment]
Your salt-api doesn't supports CORS yet, the CORS support is not yet release, it's still on develop version, sorry

**Comment by TheBigBear** [comment]
So sorry about that. 

But I did persistentmly mention that I was still running the latest released version 2015.8.3. 

And had also been asking if that might be what is stopping me. I guess I wasn't clear enough. So sorry for all the time spent on this.
 
Since this is a 'production' salt master and currently saltpad is to be considered 'alpha', I can't really afford to run a 'dev' or 'non-released' salt master version on it. 

I guess I will just have to wait for the release of 2015.8.4 along with it's new rhel/centos 6.x salt rpms.

A bit strange that @virtualguy reports it is working on his 2015.8.3 salt master? But maybe that is because he is using 'cherrypi' and has not switched to 'tornado'. 
I will now revert my salt-api back to the 'cherrypi' settings, and see what happens.

**Comment by Lothiraldan** [comment]
Sorry for the misunderstanding, it's not easy to keep "context" across different issues and different authors but I should have check that before. I will add a debug view and errors messages very soon in order to ease debug process.

Sorry about your time lost too

**Comment by TheBigBear** [comment]
@Lothiraldan I think this can be closed.
 
As the issue appears to be quite likely the version number of my salt-api being too low at 2015.8.3. 

And if running at the 2015.8.4 level, after it is released, is showing the same issue, I can always re-open it.

Thanks for all your help.
