### ISSUE TITLE
Add all config settings to settings.py or settings_local.sample.py

### ISSUE THREAD

**Issue by martinhoefling** [tinyclues/saltpad#24]
This could be useful to get quickly started, I think. If this is desired, I can prepare a pull request.

**Comment by Lothiraldan** [comment]
Yeah, I thought every settings key was set in default_settings.py, which settings is missing in your installation?

**Comment by martinhoefling** [comment]
Stuff like LOG_FILE, SENTRY_DSN and VERIFY_SSL.

**Comment by Lothiraldan** [comment]
I'm sorry, I didn't understand your issue correctly, I thought some settings were missing in default_settings.py and so saltpad couldn't start, my bad.

Just made a commit where I add SENTRY_DSN and VERIFY_SSL options in settings_local.sample.py, is it good for you?

**Comment by martinhoefling** [comment]
Yep, thats great.

**Comment by Lothiraldan** [comment]
Great, if everything is ok, could you please close the issue, I would like to experiment the idea of the issue closer should be the one that opened it.
