### ISSUE TITLE
Bind to specific IP

### ISSUE THREAD

**Issue by egilh** [tinyclues/saltpad#28]
It would be nice to have an easy way to configure which IP-adress saltpad binds to.
Right now, it only binds to 127.0.0.1, which doesnt really work well in my enviroment at least.

Maybe there already is an easy way, but I cannot seem to find it atleast ..

**Comment by Lothiraldan** [comment]
Yeah, it should not be difficult at all, let me validate that.
By the way, the recommended deployment architecture is to put saltpad behind either nginx or apache and active SSL so Saltpad will be likely to bind to 127.0.0.1, but in testing environment it can be a problem.

**Comment by egilh** [comment]
Yeah, I was thinking of putting it behind nginx, but I wanted to test a little first.

**Comment by Lothiraldan** [comment]
@egilh I've just added a settings name "HOST" to set the binding address, it should do the job, could you give it a try and close the issue if it's works?

**Comment by yrdevops** [comment]
@Lothiraldan excellent! Seems to do the trick just fine! Thanks!

**Comment by egilh** [comment]
Yeah, posted under wrong account, but thanks!
