### ISSUE TITLE
[Poll] In highstate result page, show the percentage of failing steps, changing steps, etc..

### ISSUE THREAD

**Issue by Lothiraldan** [tinyclues/saltpad#29]
I've started to do some refactoring on the highstate result page to change the background of the panel heading of each minion to show the percentage of failing steps, requirements failing steps, etc...

I've two prototypes right now but couldn't choose between them, so I ask the community to help me.

First prototype:

![capture d ecran 2015-02-27 a 14 29 37](https://cloud.githubusercontent.com/assets/243665/6413245/bcf47d94-be8d-11e4-92a1-c6da16d37724.png)
![capture d ecran 2015-02-27 a 14 29 29](https://cloud.githubusercontent.com/assets/243665/6413246/bcf4e068-be8d-11e4-9a72-ed7d87da7d7f.png)
![capture d ecran 2015-02-27 a 14 29 06](https://cloud.githubusercontent.com/assets/243665/6413247/bcf615be-be8d-11e4-9c24-927327b68bba.png)

Second prototype:

![capture d ecran 2015-02-27 a 14 30 18](https://cloud.githubusercontent.com/assets/243665/6413236/a57cdb52-be8d-11e4-925b-ca66781a8981.png)
![capture d ecran 2015-02-27 a 14 30 16](https://cloud.githubusercontent.com/assets/243665/6413238/a585430a-be8d-11e4-986a-b75157818f88.png)
![capture d ecran 2015-02-27 a 14 30 10](https://cloud.githubusercontent.com/assets/243665/6413237/a5832ebc-be8d-11e4-9506-5fc8f64d4518.png)

The difference is subtle, in the first prototype, I apply the new background style to every minion part, in the minion list and in the minion details.

In the second one, I apply the new background style only in the minion list.

What do you think community? Let's express yourself!

**Comment by TiteiKo** [comment]
1rst prototype imho, when you have more than 3 minions you won't have to scroll all the way up to visually see the rate between success/change/fail

Why have a minion list *and* a minion details and not have each of your items in your list expandable to show the details ?

**Comment by FlorentDancy** [comment]
For the second one, if (at least) an error is raised for a minion, then all the background of the title will be red ? Is that it ?

If so, then I choose the second one, since it will be easier to identify which minions need being reviewed, what do you think ?

**Comment by Lothiraldan** [comment]
@TiteiKo The minion list is a navigation help, if you have a lot of minions, it helps you go to the right minion more quickly. And adding the new background on this list will help you to quickly see the impact of your deployment. The minion details is expanded by default on errors and changes because it's what you want to check generally.

@FlorentDancy Yes in the second prototype (and in the current version), the background color is the worst step status of a minion (if at least one error, the minion is in error state, etc...). It's also my opinion that the second prototype helps you to quickly identify the status of a minion but in both prototype the font color show the minion status anyway.

**Comment by Djiit** [comment]
Hi there, 

I choose the second one, for the exact same reason as @FlorentDancy !

**Comment by TiteiKo** [comment]
@Lothiraldan Ok in light of those explanations, 2nd one too.

**Comment by Lothiraldan** [comment]
Thank you everyone for your comments.
