### ISSUE TITLE
ImportError: No module named flask

### ISSUE THREAD

**Issue by schlagify** [tinyclues/saltpad#31]
Hi, when I get to the point of running saltpad, I get this:

```
python app.py
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from flask import Flask, redirect, render_template, url_for, session, request, flash, jsonify
ImportError: No module named flask
```

I am running Debian Wheezy and I have python-flask installed, fwiw.

**Comment by Lothiraldan** [comment]
Hi @schlagify, it's very strange, how did you install saltpad ?

Try to reinstall the dependencies with pip "pip install -r requirements" if you are using a virtualenv.

**Comment by schlagify** [comment]
Hi!  I just did a `git clone git@github.com:tinyclues/saltpad.git`, cd'd into it and directly tried running `python app.py`, which gave me the error above.   After seeing your note and realizing that there is a requirements.txt file, I created a virtualenv, ran `pip install -r requirements.txt` and voila, it works.   thanks!

**Comment by Lothiraldan** [comment]
@schlagify Great you made it works! I definitely need to add an installation guide to the readme, if everything is working right now, could you please close the issue?
