### ISSUE TITLE
saltpad doesn't work with salt-api running from rest_tornado

### ISSUE THREAD

**Issue by aboe76** [tinyclues/saltpad#40]
I'm trying to run salt-api true rest_tornado instead of rest_cherrypy.
```
rest_tornado:
  disable_ssl: True
  port: 8000
  address: 127.0.0.1
```
I can do the following on command line:
```
curl -si http://localhost:8000/login \
    -H "Accept: application/json" \
    -d username='########' \
    -d password='########' \
    -d eauth='pam'
HTTP/1.1 200 OK
Date: Wed, 11 Mar 2015 17:10:38 GMT
Content-Length: 195
Content-Type: application/json
Server: TornadoServer/4.1

{"return": [{"perms": [".*", "@runner", "@wheel", "@jobs"], "start": ##########.######, "token": "################################", "expire": ##########.######, "user": "########", "eauth": "pam"}]}# 
```

But the default saltpad can't login
```
[pid: 23258|app: 0|req: 24/24] 127.0.0.1 () {46 vars in 960 bytes} [Wed Mar 11 18:09:31 2015] GET /     static/js/dataTables.bootstrap.js => generated 0 bytes in 2 msecs (HTTP/1.1 304) 5 headers in 369 bytes (0 switches on core 0)
Exception on /login [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 68, in login
    user_token = client.login(form['username'].data, form['password'].data)
  File "./core.py", line 65, in login
    headers=headers, verify=self.verify_ssl)['return'][0]['token']
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 504, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "./core.py", line 40, in request
    response.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 831, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 400 Client Error: Bad Request
[pid: 23258|app: 0|req: 25/25] 127.0.0.1 () {48 vars in 1006 bytes} [Wed Mar 11 18:09:34 2015] POST /   login?next=%5Bu%27%2F%27%5D => generated 291 bytes in 21 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1  switches on core 0)
```

Switching to rest_cherrypy with the same settings it works.
```
rest_cherrypy:
  disable_ssl: True
  port: 8000
  host: 127.0.0.1
```

**Comment by pcdummy** [comment]
Thanks for reporting! Got the same problem.

**Comment by Lothiraldan** [comment]
Thank you for reporting, I will give it a try.

If the rest_tornado and the rest_cherrypy doesn't expose the same endpoints, it may be an issue and https://github.com/saltstack/salt/issues/13698 may be a solution.

If saltpad should be compatible with only one implementation of the API, I will likely to choose the rest_tornado one.

**Comment by Diaoul** [comment]
rest_cherrypy is the most stable one as the salt documentation says. Why would you want to use rest_tornado then?

**Comment by Lothiraldan** [comment]
@Diaoul as explained in theses slides: http://www.slideshare.net/ThomasJackson4/salt-stack-at-web-scale-better-stronger-faster, the rest_cherrypy is quite slow and limited due to it's thread-based design.

**Comment by aboe76** [comment]
Information what the salt-api with rest_cherrypy returns:
```
curl -si http://localhost:8000/login \
    -H "Accept: application/json" \
    -d username='########' \
    -d password='########' \
    -d eauth='pam'
HTTP/1.1 200 OK
Content-Length: 202
Access-Control-Expose-Headers: GET, POST
Vary: Accept-Encoding
Server: CherryPy/3.6.0
Allow: GET, HEAD, POST
Access-Control-Allow-Credentials: true
Date: Fri, 13 Mar 2015 19:39:36 GMT
Access-Control-Allow-Origin: *
X-Auth-Token: ########################################
Content-Type: application/json
Set-Cookie: session_id=########################################; expires=Sat, 14 Mar 2015 05:39:36 GMT; Path=/

{"return": [{"perms": [".*", "@runner", "@wheel", "@jobs"], "start": ##########.#####, "token": "########################################", "expire": ##########.#####, "user": "########", "eauth": "pam"}]}# 
```

So there is a difference between rest_cherrypy and rest_tornado.

**Comment by Lothiraldan** [comment]
I just test with salt_tornado and salt_tornado accept url-form-encoded data for login endpoint where salt_cherrypy accept json data. I don't known yet which one I will support or how I will support both.

**Comment by jacksontj** [comment]
Can you make a curl to reproduce the login failure in saltpad? Salt_tornado has coverage for all of this stuff-- and should have at least feature parity with rest_cherrypy, so if it is missing something (or there is a bug) I'd be more than happy to fix :)

**Comment by Lothiraldan** [comment]
@jacksontj Just tried with x-url-form-encoded for both APIs, seems to works, only cherrypy support json as input for login endpoint it seems. Will update my code then.

**Comment by Lothiraldan** [comment]
I just give it a try with rest_tornado, everything seems to works correctly, @aboe76 could you give it a try. I tried with latest salt / salt-api version 2014.7.4

**Comment by Lothiraldan** [comment]
My bad, the cherrypy server was still running, some outputs are not in the same format.

@jacksontj for example the output of /jobs/JID is this one with cherrypy:

```
{u'info': [{u'Function': u'test.ping', u'jid': u'20150417160215503784', u'Result': {u'local.local': {u'return': True}}, u'Target': u'*', u'Target-type': u'glob', u'User': u'vagrant', u'StartTime': u'2015, Apr 17 16:02:15.503784', u'Minions': [u'local.local'], u'Arguments': []}], u'return': [{u'local.local': True}]}
```

While it's this one with tornado:

```
{u'return': [{u'Function': u'test.ping', u'jid': u'20150417160215503784', u'Result': {u'local.local': {u'return': True}}, u'Target': u'*', u'Target-type': u'glob', u'User': u'vagrant', u'StartTime': u'2015, Apr 17 16:02:15.503784', u'Minions': [u'local.local'], u'Arguments': []}]}
```

Some keys are located inside `return` key with tornado while there are located in the `info` key with cherrypy.

**Comment by jacksontj** [comment]
I can ad json support, it should have it

**Comment by Lothiraldan** [comment]
It's no big deal the json support as cherrypy also support urlencoded form, which is simpler for me in the end. The different output for the same endpoint is more problematic.

**Comment by jacksontj** [comment]
Hmm, if that's the only difference I'll switch the tornado one over

**Comment by whiteinge** [comment]
FWIW, supporting urlencoded data is something of a hack and has a few
caveats. (Although the login URL is simple enough.) In general, I'd
recommend sticking with JSON for all the things.

**Comment by jacksontj** [comment]
@Lothiraldan I opened #22857 to change rest_tornado's return to match cherrypy. That was a mistake on my part-- I even copied the docs over correctly ;) In addition to the fix it includes an update to the test case, so we'll be testing this return type ;)

From my little testing (and it sounds like the same above) the encoding is all working correctly. Hopefully that should cover it all :)

**Comment by aboe76** [comment]
@Lothiraldan and @jacksontj I have tested it with the latest commit and it works, with rest_cherrypy and with rest_tornado.

**Comment by Lothiraldan** [comment]
Great if everything works, could you please close the issue?

**Comment by aboe76** [comment]
Closing in the issue.
