### ISSUE TITLE
Running Saltpad via SSL

### ISSUE THREAD

**Issue by luka-page** [tinyclues/saltpad#55]
Hi,

We are able to access our saltpad instance over the network only if we modify the default_settings file to point to 0.0.0.0 this obviously is not ideal, we'd like to be able to run it via HTTPS through a web server like Apache however we're not sure how to configure this, from the documentation we see that you can use NGINX but we have no experience with that application. Is there any steps to show how this can be done?

Thanks,

Luka

**Comment by Lothiraldan** [comment]
Hi luka-page,

the recommended way to deploy saltpad with SSL if to use a WSGI server to serve saltpad on localhost and use nginx (or apache) to listen on 0.0.0.0 with the good SSL configuration and then proxy the request to saltpad.

Here is a great article about how to deploy python application with gunicorn and nginx https://www.digitalocean.com/community/tutorials/how-to-deploy-python-wsgi-apps-using-gunicorn-http-server-behind-nginx

**Comment by chamambom** [comment]
I have followed the link you suggested but im failing to run the saltpad app.

 gunicorn -b 0.0.0.0:5000 saltpad.app:app

i wanted to see if it works before intergrating it with nginx

**Comment by Lothiraldan** [comment]
From which directory do you launch gunicorn? From this repository, could you try to run an interactive python and try to import saltpad.app (```import saltpad.app```)?

```
$> python
>>> import saltpad.app
>>> saltpad.app
<module 'saltpad.app' from 'saltpad/app.pyc'>
```

The output should looks like the one above. If it fails, it will looks like this output:

```
$> python
>>> import saltpad.app
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named saltpad.app
```

**Comment by luka-page** [comment]
We have stopped using gunicorn and started using nginx/chausette, do @chamambom still need this open?

**Comment by chamambom** [comment]
I have managed to play around with deploying flask /python apps on different webservers and i am comfortable now
