### ISSUE TITLE
Error in included vagrant setup

### ISSUE THREAD

**Issue by dgmorales** [tinyclues/saltpad#61]
Running the included vagrant setup, chaussette is giving the error below:

```
Traceback (most recent call last):
  File "/usr/local/bin/chaussette", line 9, in <module>
    load_entry_point('chaussette==1.3.0', 'console_scripts', 'chaussette')()
  File "/usr/local/lib/python2.7/dist-packages/chaussette/server.py", line 173, in main
    app = import_string(application)
  File "/usr/local/lib/python2.7/dist-packages/chaussette/util.py", line 119, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
  File "./app.py", line 8, in <module>
    from .core import HTTPSaltStackClient, ExpiredToken, Unauthorized
ValueError: Attempted relative import in non-package
```

I am very new to saltstack and even more to saltpad. I just did git clone, vagrant up, got no answer on http://localhost:5050, and traced to this error in /tmp/saltpad.log inside the vm.

I was able to run it using python run.py after chaging HOST in default_settings.py (from 127.0.0.1 to the vagrant vm IP address), but surely that isn't what you meant.

Is that specific to my env or you see it too? I am running Debian Jessie, vagrant 1.7.2 and Virtualbox 4.3.

Will try to investigate it some more and maybe propose a PR to fix it.

**Comment by Lothiraldan** [comment]
Hi @dgmorales, I will check this out right now, it's not normal.

**Comment by Lothiraldan** [comment]
Right, I see the problem, I know how to fix it.

**Comment by Lothiraldan** [comment]
It should be fixed now, could you test again?

**Comment by dgmorales** [comment]
It's indeed fixed @Lothiraldan . Thanks for the speedy response. And congrats for the project.
