### ISSUE TITLE
How can i view my SLS formulars in /srv/salt from saltpad

### ISSUE THREAD

**Issue by chamambom** [tinyclues/saltpad#75]
I am new to salt and have been learning a bit on how it can help me automate most of my infrastructure processes , and i managed to add a fimular in /srv/salt/ and im able to run int via the command line ,it there a way that i can run it on using saltpad GUI

**Comment by Lothiraldan** [comment]
Hi @chamambom, you can use the "Run page" to launch them. Menu "Execute" > "Run module". You should be able to launch everything from CLI with saltpad thanks to this page

**Comment by chamambom** [comment]
@Lothiraldan i am noticing that salt executable modules like test.ping and pkg.install etc etc are the one that can be used on this interface .... i have salt state modules that i want to run / that i have already included in the /srv/salt directly ...how can i run them via saltpad ....

right now i have created my salt formulars and included most of them in the top.sls which saltpad is able to pick ,
but how about when i want to run one formulat targeting one minion

**Comment by Lothiraldan** [comment]
When you want to launch states formulas, you're launching a module named state.highstate.

If you launch this command in the CLI:

"salt '*' state.highstate"

Just set function to "state.highstate" in saltpad's run page and it will works.

**Comment by chamambom** [comment]
I think i understand now ... is there any other way to view already existing formulars besides using templates

**Comment by Lothiraldan** [comment]
You can see the full list of **modules** in the documentation here http://docs.saltstack.com/en/latest/ref/modules/all/. There are the one that you can launch with either the CLI (salt '*' **module**.**function**) or via the saltpad's run page).

Saltpad's templates are a way to save a module execution with some parameters, like launch state.highstate on a specific set of minions.

**Comment by chamambom** [comment]
thanx.its clear now ,let me read more content on the terminology of salt.
