### ISSUE TITLE
Minions not in sync 

### ISSUE THREAD

**Issue by chamambom** [tinyclues/saltpad#76]
I have 19 minions configured on saltpad and the Check minion sync status shows that 0/19 servers are in sync ... what is supposed to be in sync

**Comment by Lothiraldan** [comment]
Yeah, the initial idea was to show how many minions would be updated if we launch a state.highstate on each of them but the cost of running the state.highstate in test mode (to check if the minion is in sync or not) is too heavy right now, maybe I could add a warning on the widget.

**Comment by chamambom** [comment]
Thanx for the feedback , will follow up closely and update accordingly .. so how do i update my saltpad files if you have made changes

**Comment by Lothiraldan** [comment]
Just update the git repo with git pull
