### ISSUE TITLE
git clone repository error 

### ISSUE THREAD

**Issue by chamambom** [tinyclues/saltpad#77]
[root@lockdown tmp]# git clone git@github.com:tinyclues/saltpad.git
Cloning into 'saltpad'...
The authenticity of host 'github.com (<no hostip for proxy command>)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[root@lockdown tmp]# 

what do i need to do

**Comment by Lothiraldan** [comment]
If you try to clone saltpad via ssh (according to the command you used), you need to be sure to have a ssh key configured, see here for more help https://help.github.com/articles/generating-ssh-keys/#step-5-test-the-connection

You could also clone the repository via HTTP using this command:

```
git clone https://github.com/tinyclues/saltpad.git
```

**Comment by chamambom** [comment]
but that still means i still need the SSH keys for git pull if ever i want to update saltpad

**Comment by Lothiraldan** [comment]
No, you can user either http or ssh to update saltpad, as it's a public repository, it will not change much between the two

**Comment by chamambom** [comment]
that will work for me .thanx
