### ISSUE TITLE
"Roles" field under "Minion Status" is empty

### ISSUE THREAD

**Issue by SHU17** [tinyclues/saltpad#82]
Hi

How do I populate the "Roles" field under minion status. It is empty right now. 

Thanks
S Hu

**Comment by SHU17** [comment]
Issue is fixed. Looks like saltpad doesn't read "roles" from /etc/salt/grains file.

**Comment by Lothiraldan** [comment]
Saltpad reads roles from grain roles, all of our minions grains are configured in /etc/salt/grains
