### ISSUE TITLE
Saltpad Error when logging in "Invalid Credentials"

### ISSUE THREAD

**Issue by lukayeh** [tinyclues/saltpad#83]
Hi,

We rebuilt our saltpad instance and since then we haven't been able to log into the application.

On screen we get:
Invalid Credentials 

In /var/log/salt/master we get the following error message:
[WARNING ][1508] Authentication failure of type "eauth" occurred.

In console when running we get:
[root@pepper saltpad-master]# python run.py
 * Running on http://172.19.33.34:5000/
 * Restarting with reloader
172.19.33.34 - - [07/Aug/2015 08:57:56] "GET / HTTP/1.1" 302 -
172.19.33.34 - - [07/Aug/2015 08:57:56] "GET /login?next=%2F HTTP/1.1" 200 -
172.19.33.34 - - [07/Aug/2015 08:58:05] "POST /login?next=%2F HTTP/1.1" 200 -

salt --versions-report gives:
Salt: 2015.5.0
Python: 2.6.6 (r266:84292, Jul 23 2015, 05:13:40)
Jinja2: 2.8
M2Crypto: 0.20.2
msgpack-python: 0.4.6
msgpack-pure: Not Installed
pycrypto: 2.0.1
libnacl: Not Installed
PyYAML: 3.10
ioflo: Not Installed
PyZMQ: 14.3.1
RAET: Not Installed
ZMQ: 3.2.5
Mako: Not Installed

We also tried this with tried 2015.5.2 and 2015.5.3

Hope you can help.

Thanks,

Luka

**Comment by Lothiraldan** [comment]
Could you try to follow the debug doc page? https://github.com/tinyclues/saltpad/blob/master/docs/debug.md#login-error

**Comment by lukayeh** [comment]
Hi,

Our response from the curl command is below:

[root@pepper ~]# curl -i -H accept=application/json -d username=amonitor -d password=amonitor -d eauth=pam http://172.19.33.34:8000/login
HTTP/1.1 401 Unauthorized
Content-Length: 742
Access-Control-Expose-Headers: GET, POST
Vary: Accept-Encoding
Server: CherryPy/3.2.2
Allow: GET, HEAD, POST
Access-Control-Allow-Credentials: true
Date: Fri, 07 Aug 2015 08:20:16 GMT
Access-Control-Allow-Origin: *
Content-Type: text/html;charset=utf-8
Set-Cookie: session_id=eac9c1c931ad39cd0f4264cb8e8d5daa2fbcc5f1; expires=Fri, 07 Aug 2015 18:20:16 GMT; Path=/

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>401 Unauthorized</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>401 Unauthorized</h2>
        <p>Could not authenticate using provided credentials</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
    <span>Powered by <a href="http://www.cherrypy.org">CherryPy 3.2.2</a></span>
    </div>
    </body>
</html>

Port 8000 is the api and 5000 is the saltpad, we haven't deployed it yet through nginx or gunicorn so this is all running locally until we resolve the issue.

Thanks,

**Comment by lukayeh** [comment]
Hi there,
