### ISSUE TITLE
Unable to run Saltpad using Gunicorn

### ISSUE THREAD

**Issue by lukayeh** [tinyclues/saltpad#89]
Hi,

When attempting to run Saltpad using Gunicorn, which I believe was stated as a option not long ago we get the following error message:
````
[2015-09-02 15:35:34 +0000] [3919] [INFO] Starting gunicorn 19.3.0
[2015-09-02 15:35:34 +0000] [3919] [ERROR] Connection in use: ('127.0.0.1', 8000)
````
This also occurs when binding to a specific port, I know this may be a gunicorn issue but thought I'd try this here first as you might be aware of a fix.

Thank-you,

**Comment by Lothiraldan** [comment]
Which command do you use to launch gunicorn?

**Comment by lukayeh** [comment]
Hi @Lothiraldan 

I was using  gunicorn app:app for testing purposes, and this has worked in the past for using:

gunicorn -b 0.0.0.0:443 --certfile=/etc/pki/tls/certs/ salt.e4bh.services.crt --keyfile=/etc/pki/tls/certs/ salt.e4bh.services.keyapp:app

But this was on a past version of pad and saltstack.

Thanks,

**Comment by Lothiraldan** [comment]
Where is located the saltpad repository or where saltpad is installed?

**Comment by lukayeh** [comment]
Hi @Lothiraldan 

It is located under /root/saltpad-master/

Thanks,

**Comment by Lothiraldan** [comment]
The wsgi path is `saltpad.app:app` when you are at the root of the repository, from where do you launch gunicorn?

**Comment by lukayeh** [comment]
Using saltpad.app.app from the above directory also returns the same error, when we run gunicorn app:app we run it from /root/saltpad-master/saltpad

**Comment by Lothiraldan** [comment]
I'm sorry, I just reread the error you paste, it tell you that the port is already taken by another process. Try using this command to identify the process which held the port:

```netstat -tulpn | grep :8000```

**Comment by lukayeh** [comment]
Hi @Lothiraldan 

No problem it returns the following

````
tcp        0      0 0.0.0.0:8000                0.0.0.0:*                   LISTEN      1862/python2.6
```

Thanks,

**Comment by Lothiraldan** [comment]
@lukayeh The process with the PID 1862 has already bound the port, could you kill it or launch gunicorn on another port?

**Comment by lukayeh** [comment]
Hi @Lothiraldan 

Closing this issue as we are now using nginx and chausette as suggested in the documentation.

Thanks,
