### ISSUE TITLE
this salt 'gui' is too hard to install (and test) - please work on generic step by step instructions

### ISSUE THREAD

**Issue by TheBigBear** [tinyclues/saltpad#95]
With this being a 'GUI', it goes without saying that newbies or people not too fond (or good) in their cmd line foo will be drawn to this, in order to get a handle on thier 'salt' setup.

But apart from playing with it on the Vagrant setup, it is just too darn difficult to bring this up on an actual local salt master deployment.

can somebody please write step by step instructions, on how to do this with a web server that is available on all major platforms, debian, ubuntu, redhat (apache I guess) and some sort of wsgi server (mod_wsgi ?) and with a 'proper' SSL backing.

There are just so many steps and pieces to connect, that unless one has days/weeks to figure out all of the above technologies, there isn't a chance in hell a newbie can explore salt using the saltpad GUI.

**Comment by TheBigBear** [comment]
To give this request more focus. 
Could you start this documentation work on a saltpad web gui to be "added" (saltstack probably won't add it, per se, but it could document how to add it after someone has followed the other getting started steps on that detailed first salt setup) to the official salt Getting started guide from  https://docs.saltstack.com/en/getstarted/ ? It uses a Vagrant file to bring up a master and a couple of slaves, and then nicely progresses to introduce important concepts?

And as long as it is updated to reflect the latest salt rel. 2015.8.x along with using the new pkgs from the "new" repo.saltstack.com, this tutorial would be quite good background to document this. ( I am working/discussing the updating of those instructions, in another issue, separate to this )

Applying all of what is referred to in https://github.com/irtnog/salt-states/issues/4#issuecomment-159596372 and https://github.com/irtnog/salt-states/issues/4#issuecomment-159599246 the apache-formulas, the salt-formulae and the saltpad-formula ans some wsgi and ssl I think would be a brilliant start to help understand how all those pieces fit together for a salt newbie.

**Comment by Lothiraldan** [comment]
Hello @TheBigBear, deploying a WSGI application is not an easy task but you're right, the documentation should be more detailed. I will try to push a draft in the next week.

Moreover, I'm working on SaltPad v2 which will be a full-js application which should be a lot easier to deploy.

**Comment by Lothiraldan** [comment]
@TheBigBear I just release a new version of saltpad which should be easier to deploy, could you take a look at the new installation instructions and tell me if it's understandable?

**Comment by TheBigBear** [comment]
@Lothiraldan thanks for this. Yes, I think this is getitng much easier to deploy. 
I have tried it on my salt-master (salt-master 2015.8.3 (Beryllium)), but I am stuck.

At first I got errors about not being able to index directories, then I realized I had not index.html in the /opt/saltpad dir.

Then I copied the index-dev.html and the index-prod.html to index.html and probed with curl to see what effect it had.

I am still getting an empty page now, any ideas what I am missing?

Can I somehow test that the login as the external_auth user works?

Here is the output of what I tried.

```
root@localhost:/opt/saltpad# cp index-dev.html index.html
cp: overwrite `index.html'? y


root@localhost:/opt/saltpad# curl -k https://localhost
<!doctype html>
<html lang="en" data-framework="react">
	<head>
		<meta charset="utf-8">
		<title>SaltPad</title>
	</head>
	<body>
		<div class="app"></div>

		<script src="/app.js"></script>
	</body>
</html>


root@localhost:/opt/saltpad# cp index-prod.html index.html
cp: overwrite `index.html'? y


root@localhost:/opt/saltpad# curl -k https://localhost
<!doctype html>
<html lang="en" data-framework="react">
	<head>
		<meta charset="utf-8">
		<title>SaltPad</title>
	</head>
	<body>
		<div class="app"></div>
	</body>
</html>

root@localhost:/opt/saltpad# curl -k https://localhost:8050
curl: (7) couldn't connect to host

root@localhost:/opt/saltpad# curl  http://localhost:8050
curl: (7) couldn't connect to host

root@localhost:/opt/saltpad# curl -k https://localhost:8000
{"clients": ["runner", "runner_async", "local_async", "local", "local_batch"], "return": "Welcome”}
```

**Comment by TheBigBear** [comment]
@Lothiraldan ah and another 'silly' question. Will the webpage prompt me for the external_auth user and credentials, like the old version did, or do I need to set the user somewhere in a config file?

**Comment by TheBigBear** [comment]
@Lothiraldan in the Readme.md you say, the salt version should be 2014.8.dev ??? 

Or do you actually mean 2015.8.dev or specifically > 2015.8.3?

**Comment by Lothiraldan** [comment]
Hi @TheBigBear, thank you for testing the new saltpad.

It's weird the dist.zip doesn't contains a index.html, I will check.

Copying the index-prod.html should do the work but you should go on your laptop browser on https://localhost:8050, the Vagrantfile redirect the guest port 80 to host port 8050.

The login page should works the same and you can test the login like before by following the debug guide: https://github.com/tinyclues/saltpad/blob/master/docs/debug.md#login-error

I made some PR on salt-api required by saltpad to works, so it means that saltpad will works with the next released saltstack version.

**Comment by TheBigBear** [comment]
@Lothiraldan need to make a correction. I did not use the zip file. I saw that there were commits after the zip file, so I sued a git pull of latest files.

So, I will now try wth the zip contents, as documented. sorry, should have told you.

But does it mean that I will have to wait for the 2015.8.4 release for my salt-master, before I can test this? I can't really deploy salt masters or minions that have not yet been released.

In debugging it get:
```
HTTP/1.1 404 Not Found
Date: Thu, 07 Jan 2016 22:04:36 GMT
Server: Apache/2.2.15 (CentOS)
Content-Length: 287
Connection: close
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /login was not found on this server.</p>
<hr>
<address>Apache/2.2.15 (CentOS) Server at localhost Port 443</address>
```

**Comment by TheBigBear** [comment]
@Lothiraldan now that I am using the dist.zip contents, I still get:
```
HTTP/1.1 404 Not Found
Date: Thu, 07 Jan 2016 22:18:35 GMT
Server: Apache/2.2.15 (CentOS)
Content-Length: 287
Connection: close
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /login was not found on this server.</p>
<hr>
<address>Apache/2.2.15 (CentOS) Server at saltpad.uk.om.org Port 443</address>
</body></html>
```
But I guess, now it is failing because of the salt-master version being 2015.8.3?

**Comment by Lothiraldan** [comment]
Yes, saltpad will not works or barely works without latest update on salt-api which are not yet release.

The configuration of the web-server is a little tricky because you need to redirect all non-existing url to index.html so the js could load and show you the corresponding page. I will try to find a working apache configuration but if you achieve to get one working, please make a pull-request to integrate it in the README.

**Comment by TheBigBear** [comment]
@Lothiraldan ok, I got an apache config which redirects all URLs to /index.html, but this does not bring up the 'login' for long? 

I still get a 'blank' page. And if I hit the 'refresh' button on my browser, I briefly get the 'login' page showing for about 2 seconds, and then it disappears and becomes a blank page again.

Do you think this should work despite the salt-master version only being at the released ver. 2015.8.3 (and NOT the 2015.8.dev one) level, or do you think the login page disappearing after 2 seconds is based on the salt-api failing to work with saltpad at this version number?

```
<Directory "/opt/saltpad">
  RewriteEngine On
  RewriteBase /
  RewriteCond %{REQUEST_FILENAME} !-f 
  RewriteCond %{REQUEST_FILENAME} !-d 
  RewriteCond %{REQUEST_URI} !index
  RewriteRule (.*) /index.html [L] 
  #FallbackResource /index.html
</Directory>
```
Note: the much simpler 'FallbackResource' which does not require mod_rewrite, requires apache/httpd version >= 2.2.16.

The above comes from my apache config file, but could also go into a '.htaccess' file in '/opt/saltpad' directory.

Once I have a working apache config I will PR it to the README.md file.

**Comment by Lothiraldan** [comment]
I don't think the salt-api should have an impact, do you have errors in the JS console?

**Comment by TheBigBear** [comment]
OK, thought so. 
Yes, I checked and I get the following errors on the web console.

```
Blocked loading mixed active content "http://fonts.googleapis.com/css?family=Roboto:400,700,900"[Learn More] login
"Download the React DevTools for a better development experience: https://fb.me/react-devtools" vendors.js:25:6319
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create vendors.js:23:8093
"Download the React DevTools for a better development experience: https://fb.me/react-devtools" app.js:32:12708
Error: Invariant Violation: setState(...): takes an object of state variables to update or a function which returns an object of state variables.
```

**Comment by TheBigBear** [comment]
The 'invariant Violation' info expanded:
```
Error: Invariant Violation: setState(...): takes an object of state variables to update or a function which returns an object of state variables.
napp.js:6:3696
setStateSelect.js:222
updateStateapp.js:46893
emithelpers.js:9
iisEventSupported.js:12
(anonymous function)
_updateHandlerisEventSupported.js:12
emithelpers.js:9
valueReactErrorUtils.js:77
(anonymous function)ReactErrorUtils.js:58
```

**Comment by Lothiraldan** [comment]
It's very weird, you have deployed the release dist inside vagrant using Apache, right?

**Comment by TheBigBear** [comment]
and with the react dev tools installed the rect debug shows me:
<img width="1101" alt="screen shot 2016-01-08 at 14 02 02" src="https://cloud.githubusercontent.com/assets/471105/12199509/7f0752ba-b610-11e5-96c0-d971ac6ed699.png">

**Comment by TheBigBear** [comment]
@Lothiraldan , no not inside vagrant. I am deploying this on my production salt-master on fully up to date centos 6.x (and all with SSL/TLS on)

**Comment by Lothiraldan** [comment]
Could you check if the xhr request to settings.json returns an error or non-json response?

**Comment by TheBigBear** [comment]
sorry, glad to check , but have no idea how I check what you ask for? I am not a js developer

**Comment by Lothiraldan** [comment]
When you open the console, you should see a "network" tab, scroll until you find settings.json request, click on it and go to "response" tab, if it couldn't find the settings.json file it may returns html and then throw an error because it's not json. On my side I will try to catch the error and show an error page.

**Comment by TheBigBear** [comment]
OK, typing error text manually, can't capture it to clipboard for pasting, but also adding screenshot. ;-)
```
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
```
screenshot:
<img width="1375" alt="settings js-json parse-error" src="https://cloud.githubusercontent.com/assets/471105/12201774/0f4b00e4-b61e-11e5-8113-c3430ce8eb31.png">

**Comment by TheBigBear** [comment]
OK, I think I am a bit further now. I now get the login page to stay on screen and not jsut flash by.
I had found in the console that it had reported JSON parsing errors in settings.json for the '#' comments, once I removed the comments, it now runs through ok.


```
{
    "API_URL": "saltpad.redacted:8050", 
    "SECURE_HTTP": true, 
    "templates": { 
        "basic": { 
            "description": "Basic template", 
            "matcher": "glob",
            "target": "*",
            "moduleFunction": "test.fib",
            "arguments": {
                "num": 10
            }   
        },  

        "version": {
            "description": "Basic version",
            "matcher": "glob",
            "target": "Celeste",
            "moduleFunction": "test.version",
            "arguments": {}
        }   
    }   
}
```
it used to be (copied from settings.json.samples):
```
{
    "API_URL": "localhost:8050", # The API URL
    "SECURE_HTTP": false, # Is the API protected by HTTPS?
    "templates": { # Templates sample
        "basic": { # Template name
            "description": "Basic template", # Template description
            "matcher": "glob",
            "target": "*",
            "moduleFunction": "test.fib",
            "arguments": {
                "num": 10
            }
        },

        "version": {
            "description": "Basic version",
            "matcher": "glob",
            "target": "Celeste",
            "moduleFunction": "test.version",
            "arguments": {}
        }
    }
}
```
And each of the comments starting with '#' had caused a parse error. 

I was comparing the settings.json file in the vagrant machine with the settings.json file I had on my live master and found API URL, the SSL status and these comments to be the only difference.

**Comment by TheBigBear** [comment]
But now if I submit the username and password for the user defined in the external_auth I get no output.

I am using SSL true. Has this been tested with SSL enabled? The reason I am asking is, because the console shows me that the OPTIONS resource fetched when I submit the login data, is not fetched using a secure connection? Is that correct, or maybe why I get no response back?

<img width="1382" alt="options- the connection used to fetch this resource was not encrypted" src="https://cloud.githubusercontent.com/assets/471105/12217218/9cfe5070-b6f1-11e5-93dd-5384f65a8851.png">

**Comment by TheBigBear** [comment]
and for each time I click on the green 'login' button I get an ```uncaught exception [object Object]``` in the console.
<img width="1010" alt="uncaught exception object object" src="https://cloud.githubusercontent.com/assets/471105/12217289/d922c4a8-b6f3-11e5-8abc-7a6dd5186656.png">

**Comment by TheBigBear** [comment]
and the react tree, looks as follows:

<img width="1412" alt="react tree" src="https://cloud.githubusercontent.com/assets/471105/12217302/48680e40-b6f4-11e5-8d4d-7ae7e92c4c0d.png">

**Comment by TheBigBear** [comment]
And if I do a curl debug, I get:
```
root@localhost:/etc/salt#  curl -k -i -H accept=application/json -d username=saltpad.uk -d password=<redacted the secret ;-)> -d eauth=pam https://saltpad.<redacted>/login
HTTP/1.1 200 OK
Date: Sat, 09 Jan 2016 17:16:17 GMT
Server: Apache/2.2.15 (CentOS)
Last-Modified: Wed, 06 Jan 2016 12:30:46 GMT
ETag: "e01f8-11a-528a985fba980"
Accept-Ranges: bytes
Content-Length: 282
Connection: close
Content-Type: text/html; charset=UTF-8

<!doctype html>
<html lang="en" data-framework="react">
	<head>
		<meta charset="utf-8">
		<title>SaltPad</title>
	<link href="/styles.css" rel="stylesheet"></head>
	<body>
		<div class="app"></div>
	<script src="/vendors.js"></script><script src="/app.js"></script></body>
</html>
```

**Comment by TheBigBear** [comment]
OK, now I installed a proper valid SSL certificate and am getting further again.

in the console I can see a mention of problems because of a cross origin request? How can I swithc that off?

<img width="1409" alt="cross-origin request" src="https://cloud.githubusercontent.com/assets/471105/12218814/f1584b28-b721-11e5-9ee8-bbc8b77be6bd.png">

Also is the 406 Not acceptable - the result of the cross origin request or somethign else?

<img width="1415" alt="options 406 not acceptable" src="https://cloud.githubusercontent.com/assets/471105/12218818/faeac51c-b721-11e5-82c1-997e446c4ac3.png">

I get these messages immedialtely after clicking on the green login button. But the web page does not change the login window just stays there.

**Comment by Lothiraldan** [comment]
Right, the json file given in example is invalid because it contains comments, I tried to make it explicit that they should be removed in README but I have more work to do on this part of the documentation.

I didn't test it specifically in SSL, requests to the API should be made with ssl if the `SECURE_HTTP` setting key is set to `true`.

The Cross-Request Origin is mandatory to allow your browser to make request to the salt-api. If is activated by the key `cors_origin: '*'` in the salt-master config. Please make sure that the cors_origin is set on the salt-master config.

**Comment by TheBigBear** [comment]
@Lothiraldan cors_origin: is set in master file. Any ideas on how to debug this?
Here is a screenshot of the console in chrome.

<img width="1338" alt="cors_origin 406 unaceptable" src="https://cloud.githubusercontent.com/assets/471105/12280041/1108fad6-b983-11e5-8767-0decb5258e25.png">

**Comment by TheBigBear** [comment]
I have also enabled debug in the master file, and this is the master log fierl content:

```
2016-01-12 21:46:38,976 [root                                               ][CRITICAL][3394] init a listener
2016-01-12 21:46:38,990 [tornado.access                                     ][WARNING ][3394] 406 OPTIONS /login (10.37.128.11) 15.09ms
2016-01-12 22:22:22,091 [tornado.access                                     ][WARNING ][3394] 406 OPTIONS /login (10.37.128.11) 1.64ms
2016-01-12 22:31:58,775 [root                                               ][CRITICAL][7892] init a listener
2016-01-12 22:31:58,797 [tornado.access                                     ][WARNING ][7892] 406 OPTIONS /login (10.37.128.11) 22.97ms
2016-01-12 22:32:01,386 [tornado.access                                     ][WARNING ][7892] 406 OPTIONS /login (10.37.128.11) 1.04ms
2016-01-12 22:35:53,265 [root                                               ][CRITICAL][10666] init a listener
2016-01-12 22:35:53,276 [tornado.access                                     ][WARNING ][10666] 406 OPTIONS /login (10.37.128.11) 11.32ms
2016-01-12 22:36:01,217 [tornado.access                                     ][WARNING ][10666] 406 OPTIONS /login (10.37.128.11) 1.00ms
2016-01-12 22:41:51,399 [tornado.access                                     ][WARNING ][10666] 406 OPTIONS /login (10.37.128.11) 1.30ms
2016-01-12 22:46:42,265 [root                                               ][CRITICAL][17765] init a listener
2016-01-12 22:46:42,284 [tornado.access                                     ][WARNING ][17765] 406 OPTIONS /login (10.37.128.11) 20.61ms
2016-01-12 22:46:49,058 [tornado.access                                     ][WARNING ][17765] 406 OPTIONS /login (10.37.128.11) 1.07ms
2016-01-12 23:00:59,634 [tornado.access                                     ][WARNING ][17765] 406 POST /login (10.37.128.11) 2.74ms
2016-01-12 23:00:59,636 [tornado.general                                    ][ERROR   ][17765] Cannot send error response after headers written
2016-01-12 23:05:25,173 [tornado.access                                     ][WARNING ][17765] 406 POST /login (10.37.128.11) 2.01ms
2016-01-12 23:05:25,173 [tornado.general                                    ][ERROR   ][17765] Cannot send error response after headers written
2016-01-12 23:07:23,399 [tornado.access                                     ][WARNING ][17765] 406 POST /login (10.37.128.11) 1.42ms
2016-01-12 23:07:23,403 [tornado.general                                    ][ERROR   ][17765] Cannot send error response after headers written
```

**Comment by TheBigBear** [comment]
I might be way off track, very likley even. But I find comments about it not being possible to use wildcards wirth cors_origin if and when credentials are in play? Coud that be part of the block here?
see 
https://stackoverflow.com/questions/26411480/angularjs-a-wildcard-cannot-be-used-in-the-access-control-allow-origin-he

**Comment by virtualguy** [comment]
I got stuck on most the the same issues above when trying to set up a test install under apache. I have collected the relevant notes and submitted as a PR #113 . However as I am not yet using SSL for saltpad I am now able to successfully log in and haven't hit any further issues

**Comment by TheBigBear** [comment]
@virtualguy thank you so much, appreciate you collecting it and putting it together. I was going to do it once I got a working setup, honest. ;-) 

One question, what version is your salt master at?

**Comment by virtualguy** [comment]
I'm running 2015.8.3. Though it appears that might not be recent enough. See #114

**Comment by Lothiraldan** [comment]
Thank you @virtualguy for the apache config, I am more a nginx guy. About the wildcard cors support @TheBigBear, technically browsers doesn't support a wildcard in the header but when salt-api is configured with "*", it simply allow every request basically so it should works.

**Comment by TheBigBear** [comment]
@Lothiraldan I think this can now be closed. 

The original issue has certainly been achieved once the new saltpad one page app ("v2") and it's readme.md had been published, and the rest of the issue(s) above were all to do with improving on the readme.md and the struggles in the latter part with the new v2 saltpad not running would in the main appear to be directly related to the version number of my salt-api not being high enough at 2015.8.3.
